Minor backend changes
teknikfokus/fair.teknikfokus.se pull request #14
Opened 2022-01-28 11:07 UTC by FredrikHessner

2022-01-28 12:22 UTC, AntiSC2 requested changes

2022-01-28 12:22 UTC, AntiSC2 commented on package-lock.json
> +  "lockfileVersion": 1,
Det här kanske är problematisk att vi ändrar lockfileVersion. Vi borde hålla oss till 2 då det är backwards compatible med npm v6 men npm v7 och v8 använder sig av det nyare formatet automatiskt.

2022-01-28 13:16 UTC, FredrikHessner commented on package-lock.json
> +  "lockfileVersion": 1,
Ändrar till 2

2022-01-29 15:24 UTC, AntiSC2 approved these changes

2022-01-29 16:06 UTC, merged