User profile - Companies
teknikfokus/fair.teknikfokus.se pull request #9
Opened 2022-01-23 19:19 UTC by FredrikHessner

- MVC for user profile
- Adds foreign key to company user which links back to company profile
- Added upload image as a separate HTTP request.

2022-01-23 19:25 UTC, AntiSC2 requested changes

2022-01-23 19:25 UTC, AntiSC2 commented on src/user-profile/helpers/image-storage.ts
> +export const isFileExtensionSafe = (
Ta bort utkommenterad funktion?

2022-01-23 19:25 UTC, AntiSC2 commented on src/user-profile/controllers/company_profile.controller.ts
> +
Indentation?

2022-01-23 19:25 UTC, AntiSC2 commented on src/auth/services/student_auth.service.ts
> +
formatering

2022-01-25 16:07 UTC, Joel-Jensen approved these changes

2022-01-25 16:13 UTC, AntiSC2 approved these changes

2022-01-26 07:32 UTC, merged